source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'sqlite3'
gem 'devise'
gem "twitter-bootstrap-rails"
gem 'jquery-rails'
gem "meta_search"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem "rails-erd"
end